// GENERADO por scripts/productos-digitales/sync-payment-links.py — NO editar a mano.
// productId → URL pública del Payment Link de Stripe (la misma que Vite inlina en la landing).
// Regenerar tras cambiar cualquier VITE_STRIPE_PAYMENT_LINK_* en Netlify; el gate --check avisa del drift.
export const PAYMENT_LINKS: Record<string, string> = {
  'guia-dark-kitchen': 'https://buy.stripe.com/eVq5kw6WoboybnpdfD6oo0L',
  'guia-panaderia-obrador': 'https://buy.stripe.com/dRm6oAbcE78iajl2AZ6oo1e',
  'guia-restaurante-casual': 'https://buy.stripe.com/bJefZa1C49gqgHJdfD6oo0N',
  'guia-restaurante-gastronomico': 'https://buy.stripe.com/14A28k5Sk50a7796Rf6oo0M',
  'guia-restaurante-japones': 'https://buy.stripe.com/eVq9AM6WoeAKezBejH6oo0Q',
  'guia-restaurante-mexicano': 'https://buy.stripe.com/4gM8wIgwY2S2fDFejH6oo0O',
  'guia-restaurante-nikkei': 'https://buy.stripe.com/aFa4gs1C464e0ILfnL6oo10',
  'guia-restaurante-peruano': 'https://buy.stripe.com/6oUbIU2G80JU0ILa3r6oo0P',
  'kit-escandallos': 'https://buy.stripe.com/cNi3cogwY64e9fhfnL6oo01',
  'kit-gestion-personal': 'https://buy.stripe.com/00weV64Og0JUezB2AZ6oo0H',
  'kit-inventario': 'https://buy.stripe.com/3cI6oA0y01NYbnp1wV6oo0I',
  'kit-plan-financiero': 'https://buy.stripe.com/dRm00cgwY3W60IL1wV6oo0J',
  'kit-tareas': 'https://buy.stripe.com/fZucMYeoQ0JU3UXgrP6oo03',
  'kit-tareas-asador': 'https://buy.stripe.com/fZu6oA5Sk1NY9fh3F36oo0Y',
  'kit-tareas-bar': 'https://buy.stripe.com/28EdR21C4eAK3UXejH6oo09',
  'kit-tareas-cafeteria': 'https://buy.stripe.com/28EbIU6Wo50a8bd2AZ6oo04',
  'kit-tareas-catering': 'https://buy.stripe.com/bJefZagwYeAK8bd5Nb6oo0a',
  'kit-tareas-chef-privado': 'https://buy.stripe.com/7sY5kw4OgdwG9fhcbz6oo0f',
  'kit-tareas-chocolateria': 'https://buy.stripe.com/bJe6oA94w9gqezB1wV6oo0e',
  'kit-tareas-dark-kitchen': 'https://buy.stripe.com/aFa6oA4Og3W6dvx8Zn6oo07',
  'kit-tareas-food-truck': 'https://buy.stripe.com/6oU8wIbcE0JU4Z16Rf6oo12',
  'kit-tareas-hamburgueseria': 'https://buy.stripe.com/7sY00c94wdwG7793F36oo06',
  'kit-tareas-heladeria': 'https://buy.stripe.com/cNi3coa8A9gq1MP3F36oo0d',
  'kit-tareas-hotel': 'https://buy.stripe.com/9B6bIU80sfEO0IL1wV6oo0c',
  'kit-tareas-marisqueria': 'https://buy.stripe.com/aFa8wI1C450a2QT2AZ6oo0Z',
  'kit-tareas-panaderia': 'https://buy.stripe.com/6oUbIUdkM9gqajldfD6oo13',
  'kit-tareas-pasteleria': 'https://buy.stripe.com/6oU7sEeoQ9gq3UX0sR6oo08',
  'kit-tareas-pizzeria': 'https://buy.stripe.com/3cI9AM80saku4Z11wV6oo05',
  'kit-tareas-restaurante-creativo': 'https://buy.stripe.com/28E00c3Kc1NY6357Vj6oo0g',
  'kit-tareas-sushi-bar': 'https://buy.stripe.com/14AfZa94w2S20IL1wV6oo0X',
  'kit-tareas-tapas-bar': 'https://buy.stripe.com/28E14gfsU50a8bd7Vj6oo11',
  'mega-pack-tareas': 'https://buy.stripe.com/6oU5kwdkM78i3UXb7v6oo0K',
  'pack-appcc': 'https://buy.stripe.com/3cI28kbcE9gqezB0sR6oo02',
  'plan-catering-tematico-eventos': 'https://buy.stripe.com/dRm9AMa8A78i6352AZ6oo1d',
  'plan-chef-privado-showcooking-eventos': 'https://buy.stripe.com/aFadR24OgcsCezBa3r6oo1c',
  'plan-negocio-bar-restaurante': 'https://buy.stripe.com/6oU4gs2G80JU9fh1wV6oo14',
  'plan-negocio-cafeteria': 'https://buy.stripe.com/8x27sE1C450a1MPejH6oo16',
  'plan-negocio-cocteleria-eventos': 'https://buy.stripe.com/cNi6oA80seAK8bdfnL6oo19',
  'plan-negocio-food-truck': 'https://buy.stripe.com/28EfZadkMfEOajl8Zn6oo18',
  'plan-negocio-paellero-eventos': 'https://buy.stripe.com/4gMdR2dkMeAKajlfnL6oo1b',
  'plan-negocio-panaderia': 'https://buy.stripe.com/7sY00ca8A0JUezBejH6oo17',
  'plan-negocio-parrillero-asador-eventos': 'https://buy.stripe.com/cNi6oAa8A50a4Z1cbz6oo1a',
  'plan-negocio-tapas-bar': 'https://buy.stripe.com/aFadR21C4eAK8bd5Nb6oo15',
  'pro-prompts-ebook': 'https://buy.stripe.com/7sYfZafsU8cm3UX7Vj6oo00',
};

/** URL → productId (para el webhook: la sesión trae payment_link, no el producto). */
export const PRODUCT_BY_LINK: Record<string, string> = Object.fromEntries(
  Object.entries(PAYMENT_LINKS).map(([pid, url]) => [url, pid]),
);
