// GENERADO por scripts/productos-digitales/sync-product-prices.py — NO editar a mano.
// productId → precio anunciado en la landing (schema.price de la ficha), en EUR. Es el importe con el que
// crypto-checkout crea la invoice de NOWPayments: el precio es el mismo para todos los países (decisión de John 2026-09-05).
export const PRODUCT_PRICES: Record<string, { eur: number }> = {
  'guia-dark-kitchen': { eur: 24 },
  'guia-food-cost-ingenieria-menu': { eur: 55 },
  'guia-panaderia-obrador': { eur: 65 },
  'guia-restaurante-casual': { eur: 65 },
  'guia-restaurante-gastronomico': { eur: 85 },
  'guia-restaurante-japones': { eur: 65 },
  'guia-restaurante-mexicano': { eur: 65 },
  'guia-restaurante-nikkei': { eur: 65 },
  'guia-restaurante-peruano': { eur: 65 },
  'kit-escandallos': { eur: 12 },
  'kit-gestion-personal': { eur: 14 },
  'kit-inventario': { eur: 14 },
  'kit-plan-financiero': { eur: 39 },
  'kit-tareas': { eur: 14 },
  'kit-tareas-asador': { eur: 14 },
  'kit-tareas-bar': { eur: 12 },
  'kit-tareas-cafeteria': { eur: 12 },
  'kit-tareas-catering': { eur: 12 },
  'kit-tareas-chef-privado': { eur: 18 },
  'kit-tareas-chocolateria': { eur: 12 },
  'kit-tareas-dark-kitchen': { eur: 12 },
  'kit-tareas-food-truck': { eur: 12 },
  'kit-tareas-hamburgueseria': { eur: 12 },
  'kit-tareas-heladeria': { eur: 12 },
  'kit-tareas-hotel': { eur: 18.5 },
  'kit-tareas-marisqueria': { eur: 14 },
  'kit-tareas-panaderia': { eur: 12 },
  'kit-tareas-pasteleria': { eur: 12 },
  'kit-tareas-pizzeria': { eur: 12 },
  'kit-tareas-restaurante-creativo': { eur: 12 },
  'kit-tareas-sushi-bar': { eur: 14 },
  'kit-tareas-tapas-bar': { eur: 14 },
  'manual-manager-restaurante': { eur: 55 },
  'mega-pack-tareas': { eur: 89 },
  'pack-appcc': { eur: 14 },
  'plan-catering-tematico-eventos': { eur: 45 },
  'plan-chef-privado-showcooking-eventos': { eur: 45 },
  'plan-negocio-bar-restaurante': { eur: 35 },
  'plan-negocio-cafeteria': { eur: 29 },
  'plan-negocio-cocteleria-eventos': { eur: 55 },
  'plan-negocio-food-truck': { eur: 29 },
  'plan-negocio-paellero-eventos': { eur: 45 },
  'plan-negocio-panaderia': { eur: 35 },
  'plan-negocio-parrillero-asador-eventos': { eur: 45 },
  'plan-negocio-tapas-bar': { eur: 35 },
  'pro-prompts-ebook': { eur: 9 },
};
