# -*- coding: utf-8 -*-
"""Contenido F2 — REDACTOR A — kit-tareas-taqueria.

Cubre los ficheros 01, 02, 03 y 04 (10 hojas de checklist). Ver
02-SPEC-kit-tareas-taqueria.md §3 (01-04) y §4 (reglas de redaccion).

Clave = nombre EXACTO de la hoja. Valor = lista de secciones
(NOMBRE_SECCION, [(tarea, zona, responsable, hora), ...]).
Las tareas van en forma final (D14/D15: espacio normal antes de la
unidad, signo menos U+2212) para que el motor no las reescriba.
"""

SEC = {

    # ------------------------------------------------------------------
    # 01 - 01-apertura-cierre-taqueria.xlsx
    # ------------------------------------------------------------------

    'Apertura Taquería': [
        ('TEMPERATURAS Y EQUIPOS', [
            ('Registrar temperatura de la cámara de carne marinada (≤ 4 °C) — anota la lectura: ____ °C',
             'Cámara', 'Encargado', '10:30'),
            ('Registrar temperatura del congelador (≤ −18 °C) — anota la lectura: ____ °C',
             'Cámara', 'Encargado', '10:32'),
            ('Registrar temperatura de la cámara de salsas y vegetales (≤ 4 °C) — anota la lectura: ____ °C',
             'Barra', 'Encargado', '10:34'),
            ('Comprobar que el expositor de la barra de salsas mantiene ≤ 4 °C antes de abrir',
             'Barra', 'Mostrador', '10:40'),
            ('Calibrar la sonda de temperatura del turno y anotar la desviación medida',
             'Cocina', 'Encargado', '10:42'),
            ('Comprobar el funcionamiento de la campana extractora y el sistema de extracción',
             'Cocina', 'Plancha', '10:45'),
        ]),
        ('TROMPO, PLANCHA Y COMAL', [
            ('Encender el trompo (asador vertical) y comprobar llama uniforme en todos los quemadores',
             'Cocina', 'Taquero', '10:50'),
            ('Montar el trompo del día: orden de capas, grasa, piña y cebolla; anotar peso y hora',
             'Cocina', 'Taquero', '11:00'),
            ('Comprobar el cono recibido a ≤ −18 °C si congelado o ≤ 4 °C si refrigerado',
             'Cocina', 'Taquero', '11:05'),
            ('Calibrar plancha y comal por zonas (alta y media) y anotar la temperatura de trabajo',
             'Cocina', 'Plancha', '11:10'),
            ('Comprobar el nivel y el estado del aceite de la freidora antes del servicio',
             'Cocina', 'Plancha', '11:12'),
            ('Afilar el cuchillo de corte del trompo y dejarlo listo en su funda',
             'Cocina', 'Taquero', '11:15'),
        ]),
        ('SALSAS Y GUARNICIONES', [
            ('Sacar las salsas crudas a la barra fría y comprobar ≤ 4 °C antes de abrir',
             'Barra', 'Mostrador', '11:20'),
            ('Verificar que el cartel de alérgenos está visible y marca la salsa macha (cacahuete y/o sésamo)',
             'Barra', 'Mostrador', '11:22'),
            ('Reponer cebolla, cilantro y limón en recipientes limpios, nunca sobre el resto anterior',
             'Barra', 'Mostrador', '11:25'),
            ('Preparar la salsa macha (cacahuete y/o sésamo) del día y etiquetarla con fecha y hora',
             'Cocina', 'Plancha', '11:28'),
            ('Comprobar que cada salsa tiene su utensilio propio y que ninguno se comparte con la macha',
             'Barra', 'Mostrador', '11:30'),
            ('Montar el encurtido de cebolla morada y jalapeños y etiquetarlo con fecha',
             'Cocina', 'Plancha', '11:32'),
        ]),
        ('TORTILLA Y GUISADOS', [
            ('Poner los guisados (cazuelas de relleno) en baño maría y comprobar ≥ 63 °C',
             'Cocina', 'Plancha', '11:35'),
            ('Calentar el comal y calibrar el grosor de la primera tanda de tortilla de maíz',
             'Tortillería', 'Tortillero/a', '11:38'),
            ('Comprobar la reserva de tortilla de harina y de tortilla de maíz por separado',
             'Tortillería', 'Tortillero/a', '11:40'),
            ('Anotar la hora de entrada en baño maría de cada guisado (cazuelas de relleno)',
             'Cocina', 'Plancha', '11:42'),
            ('Revisar el stock de limón, sal y salsas embotelladas de la barra',
             'Barra', 'Mostrador', '11:45'),
        ]),
        ('SALA, MOSTRADOR Y DELIVERY', [
            ('Abrir el TPV y comprobar el fondo de caja inicial',
             'Mostrador', 'Mostrador', '11:48'),
            ('Revisar mesas, barra y exterior: limpieza, sillas y cartelería',
             'Sala', 'Todo el equipo', '11:50'),
            ('Comprobar que las apps de delivery están activas y con la carta actualizada',
             'Mostrador', 'Mostrador', '11:52'),
            ('Revisar la previsión de reservas y grupos del turno',
             'Sala', 'Encargado', '11:55'),
            ('Hacer el briefing pre-servicio con el equipo: trompo del día, guisados y salsas',
             'Cocina', 'Encargado', '11:58'),
        ]),
    ],

    'Cierre Taquería': [
        ('TROMPO Y PLANCHA', [
            ('Apagar el trompo (asador vertical) al cierre',
             'Cocina', 'Taquero', '23:00'),
            ('Retirar la carne sobrante del trompo y registrar su destino: abatida o descartada',
             'Cocina', 'Taquero', '23:05'),
            ('Vaciar, lavar y desinfectar la bandeja de grasas del asador vertical',
             'Cocina', 'Taquero', '23:10'),
            ('Rascar y engrasar la plancha en caliente; limpiar el comal antes de que enfríe',
             'Cocina', 'Plancha', '23:15'),
            ('Filtrar el aceite de la freidora y anotar la fecha del último cambio',
             'Cocina', 'Plancha', '23:18'),
            ('Guardar el cuchillo de corte del trompo limpio y en su funda',
             'Cocina', 'Taquero', '23:20'),
        ]),
        ('SALSAS Y GUISADOS', [
            ('Descartar las salsas crudas del día y anotar la merma en litros',
             'Barra', 'Mostrador', '23:25'),
            ('Descartar la salsa macha (cacahuete y/o sésamo) sobrante del día',
             'Barra', 'Mostrador', '23:28'),
            ('Abatir el guisado apto y etiquetarlo con fecha y hora',
             'Cocina', 'Plancha', '23:30'),
            ('Descartar el guisado no apto y anotar el motivo',
             'Cocina', 'Plancha', '23:33'),
            ('Guardar la tortilla de maíz y la de harina sobrantes en recipientes separados',
             'Tortillería', 'Tortillero/a', '23:35'),
        ]),
        ('LIMPIEZA Y RESIDUOS', [
            ('Limpiar y desinfectar la barra de salsas por completo',
             'Barra', 'Mostrador', '23:40'),
            ('Sacar la basura y separar los residuos según la normativa del municipio',
             'Exterior', 'Todo el equipo', '23:42'),
            ('Limpiar y desinfectar la licuadora y el molcajete del turno',
             'Cocina', 'Plancha', '23:45'),
            ('Barrer y fregar cocina, barra y sala antes del cierre',
             'Cocina', 'Todo el equipo', '23:48'),
            ('Revisar que no quedan cuchillos ni utensilios fuera de su sitio',
             'Cocina', 'Encargado', '23:50'),
            ('Comprobar que la puerta de la cámara y el congelador cierran bien',
             'Cámara', 'Encargado', '23:52'),
        ]),
        ('CAJA Y CIERRE DE NEGOCIO', [
            ('Hacer el arqueo de caja y anotar cualquier descuadre',
             'Mostrador', 'Encargado', '23:55'),
            ('Repartir las propinas del turno entre el equipo',
             'Mostrador', 'Encargado', '00:00'),
            ('Cerrar el canal de delivery en todas las apps activas',
             'Mostrador', 'Mostrador', '00:03'),
            ('Revisar que la hoja de temperaturas del turno queda firmada y archivada',
             'Cocina', 'Encargado', '00:05'),
            ('Apagar luces, activar la alarma y cerrar la puerta principal',
             'Sala', 'Encargado', '00:10'),
        ]),
    ],

    # ------------------------------------------------------------------
    # 02 - 02-trompo-plancha-comal.xlsx
    # ------------------------------------------------------------------

    'Marinado y Montaje del Trompo': [
        ('MARINADO (VÍSPERA)', [
            ('Pesar carne y adobo por lote; anotar número de lote y hora de inicio del marinado',
             'Cocina', 'Taquero', '19:00'),
            ('Mantener el marinado a ≤ 4 °C el tiempo definido en tu ficha: ______ h',
             'Cámara', 'Taquero', '19:05'),
            ('Registrar el proveedor y el lote del cerdo y del adobo utilizados',
             'Cocina', 'Encargado', '19:02'),
            ('Comprobar que el recipiente del marinado queda tapado y etiquetado',
             'Cámara', 'Taquero', '19:10'),
            ('Remover el lote a mitad del marinado y anotar la hora',
             'Cámara', 'Taquero', '20:00'),
            ('Registrar la temperatura de la cámara donde reposa el marinado — anota la lectura: ____ °C',
             'Cámara', 'Taquero', '19:15'),
        ]),
        ('MONTAJE DEL TROMPO (SI APLICA)', [
            ('Comprobar el cono recibido: ≤ −18 °C si congelado, ≤ 4 °C si refrigerado',
             'Cocina', 'Taquero', '09:30'),
            ('Montar el trompo (asador vertical): capas, grasa, piña y cebolla; anotar peso total',
             'Cocina', 'Taquero', '09:45'),
            ('Anotar la hora de montaje y la hora límite definida en tu APPCC (HACCP): ______',
             'Cocina', 'Taquero', '09:50'),
            ('Comprobar que el trompo queda centrado y equilibrado sobre el eje',
             'Cocina', 'Taquero', '09:55'),
            ('Esperar a que la capa exterior esté cocinada antes del primer corte',
             'Cocina', 'Taquero', '10:15'),
            ('Registrar la temperatura de la capa exterior antes del primer corte — anota la lectura: ____ °C',
             'Cocina', 'Taquero', '10:20'),
        ]),
        ('RENDIMIENTO', [
            ('Anotar el peso sobrante del trompo al cierre y calcular el rendimiento en tacos por kilo',
             'Cocina', 'Encargado', '23:30'),
            ('Anotar la merma de grasa y recortes del trompo del día',
             'Cocina', 'Taquero', '23:20'),
            ('Comparar el rendimiento del día con la media de la semana y anotar la desviación',
             'Cocina', 'Encargado', '23:35'),
            ('Registrar el número de conos montados y consumidos en el turno',
             'Cocina', 'Encargado', '23:40'),
            ('Revisar el rendimiento del marinado: kilos de carne por lote frente a tacos servidos',
             'Cocina', 'Encargado', '23:45'),
            ('Registrar cualquier incidencia del trompo del día para el parte de mantenimiento',
             'Cocina', 'Encargado', '23:50'),
        ]),
    ],

    'Corte, Plancha y Comal': [
        ('SONDA Y CORTE (SI APLICA)', [
            ('Sondar la capa exterior antes de cada tanda de corte — anota la lectura: ____ °C (≥ 70 °C)',
             'Cocina', 'Taquero', '11:00'),
            ('Registrar la sonda al inicio y a mitad del servicio, como mínimo',
             'Cocina', 'Taquero', '11:05'),
            ('Cortar sólo la capa cocinada; no rebanar hacia el interior todavía crudo',
             'Cocina', 'Taquero', '11:10'),
            ('Anotar la hora límite del fileteado definida en tu APPCC (HACCP): ______',
             'Cocina', 'Taquero', '11:15'),
            ('Limpiar cuchillo y tabla del trompo antes de tocar producto listo para consumo',
             'Cocina', 'Taquero', '11:20'),
        ]),
        ('PLANCHA', [
            ('Pasar a mantenimiento ≥ 63 °C la carne cortada que no se sirve al momento; nunca a ambiente',
             'Cocina', 'Plancha', '11:25'),
            ('Comprobar la temperatura de trabajo de la plancha por zonas y anotarla',
             'Cocina', 'Plancha', '11:30'),
            ('Dorar los tacos y quesadillas a la plancha sin mezclar tandas de carne distintas',
             'Cocina', 'Plancha', '11:35'),
            ('Limpiar la plancha entre tandas para evitar que se acumule grasa quemada',
             'Cocina', 'Plancha', '11:40'),
        ]),
        ('COMAL', [
            ('Registrar las mermas de tortilla de maíz del comal por turno',
             'Tortillería', 'Tortillero/a', '11:45'),
            ('Calentar la tortilla de maíz y la de harina en zonas separadas del comal',
             'Tortillería', 'Tortillero/a', '11:50'),
            ('Comprobar que el comal mantiene temperatura uniforme y anotar cualquier zona fría',
             'Tortillería', 'Tortillero/a', '11:55'),
            ('Doblar y guardar la tortilla de maíz calentada en el cajón térmico hasta el servicio',
             'Tortillería', 'Tortillero/a', '12:00'),
            ('Limpiar los restos de masa del comal entre tandas',
             'Tortillería', 'Tortillero/a', '12:05'),
        ]),
        ('CONTAMINACIÓN CRUZADA', [
            ('Usar tabla y cuchillo distintos para carne cruda y carne ya cocinada del trompo',
             'Cocina', 'Taquero', '12:10'),
            ('Separar pinzas y bandejas de la tortilla de harina (gluten) de las de maíz',
             'Tortillería', 'Tortillero/a', '12:15'),
            ('Lavarse las manos entre la manipulación del cono crudo y del producto cortado',
             'Cocina', 'Taquero', '12:20'),
            ('Comprobar que ningún utensilio de la salsa macha (cacahuete y/o sésamo) toca otra salsa',
             'Cocina', 'Plancha', '12:25'),
        ]),
    ],

    # ------------------------------------------------------------------
    # 03 - 03-appcc-salsas-alergenos.xlsx
    # ------------------------------------------------------------------

    'Temperaturas y Trazabilidad': [
        ('TEMPERATURAS (2 VECES POR TURNO)', [
            ('Registrar cámaras de refrigeración (≤ 4 °C) dos veces por turno — anota la lectura: ____ °C',
             'Cámara', 'Encargado', '11:00'),
            ('Registrar el congelador (≤ −18 °C) dos veces por turno — anota la lectura: ____ °C',
             'Cámara', 'Encargado', '11:02'),
            ('Comprobar que los guisados (cazuelas de relleno) están en baño maría antes de cada lectura',
             'Cocina', 'Plancha', '11:03'),
            ('Registrar el baño maría de guisados (≥ 63 °C) dos veces por turno — anota la lectura: ____ °C',
             'Cocina', 'Plancha', '11:04'),
            ('Registrar la barra fría de salsas (≤ 4 °C) dos veces por turno — anota la lectura: ____ °C',
             'Barra', 'Mostrador', '11:06'),
            ('Calibrar la sonda de temperatura al inicio del turno y anotar el resultado',
             'Cocina', 'Encargado', '11:10'),
        ]),
        ('RECEPCIÓN Y TRAZABILIDAD', [
            ('Anotar lote y proveedor de la carne de pastor, de la masa o tortilla y de los chiles secos',
             'Recepción', 'Encargado', '09:00'),
            ('Registrar cada recepción: temperatura, estado del envase, caducidad y número de albarán',
             'Recepción', 'Encargado', '09:05'),
            ('Comprobar que el cono del trompo (asador vertical) llega a ≤ −18 °C si congelado o ≤ 4 °C si refrigerado',
             'Recepción', 'Taquero', '09:10'),
            ('Rechazar y anotar cualquier recepción fuera de rango o con el envase dañado',
             'Recepción', 'Encargado', '09:15'),
            ('Etiquetar cada producto recibido con proveedor, lote y fecha de caducidad',
             'Almacén', 'Encargado', '09:20'),
            ('Archivar los albaranes del día para la trazabilidad del turno',
             'Almacén', 'Encargado', '09:25'),
        ]),
        ('CONGELACIÓN DE CRUDOS (SI APLICA) Y RECALENTADO', [
            ('Verificar la congelación del pescado crudo de aguachiles y tostadas: −20 °C/24 h o −35 °C/15 h',
             'Cámara', 'Encargado', '09:30'),
            ('Etiquetar el pescado congelado en preventiva con fecha de inicio y de fin del proceso',
             'Cámara', 'Encargado', '09:35'),
            ('Registrar la hora de inicio y de fin del proceso de congelación preventiva del pescado',
             'Cámara', 'Encargado', '09:40'),
            ('Recalentar los guisados a ≥ 74 °C durante 15 s en el centro, en menos de 1 hora',
             'Cocina', 'Plancha', '12:00'),
            ('Comprobar que el recalentado sale del frigorífico y alcanza su temperatura en el término de 1 hora',
             'Cocina', 'Plancha', '12:05'),
            ('Descartar cualquier recalentado que no alcance ≥ 74 °C durante 15 s en el centro',
             'Cocina', 'Plancha', '12:10'),
        ]),
    ],

    'Barra de Salsas': [
        ('MONTAJE DE LA BARRA', [
            ('Medir la temperatura de pico de gallo, guacamole y salsas crudas — anota la lectura: ____ °C (≤ 4 °C)',
             'Barra', 'Mostrador', '11:15'),
            ('Anotar la hora de puesta en barra de cada salsa y su hora de descarte',
             'Barra', 'Mostrador', '11:18'),
            ('Comprobar que cada salsa lleva su etiqueta con nombre y nivel de picante',
             'Barra', 'Mostrador', '11:20'),
            ('Verificar que el cartel de alérgenos marca la salsa macha (cacahuete y/o sésamo) en la barra',
             'Barra', 'Mostrador', '11:22'),
            ('Comprobar que cada salsa tiene su cuchara o pinza propia antes de abrir',
             'Barra', 'Mostrador', '11:25'),
        ]),
        ('REPOSICIÓN POR TANDAS', [
            ('Reponer por tandas pequeñas en recipiente limpio; PROHIBIDO rellenar sobre el resto anterior',
             'Barra', 'Mostrador', '13:00'),
            ('Cambiar cucharas y pinzas de cada salsa por turno y registrar el cambio',
             'Barra', 'Mostrador', '13:05'),
            ('Revisar visualmente la barra cada turno: restos, derrames y manipulación por el cliente',
             'Barra', 'Mostrador', '13:10'),
            ('Reponer la salsa macha (cacahuete y/o sésamo) sin mezclar el recipiente nuevo con el usado',
             'Barra', 'Mostrador', '13:15'),
            ('Comprobar la temperatura de la barra a mitad de servicio — anota la lectura: ____ °C',
             'Barra', 'Mostrador', '14:00'),
        ]),
        ('DESCARTE Y MERMA', [
            ('Descartar al cierre las salsas crudas del día y anotar la merma',
             'Barra', 'Mostrador', '23:20'),
            ('Descartar la salsa macha (cacahuete y/o sésamo) sobrante y anotar la cantidad',
             'Barra', 'Mostrador', '23:22'),
            ('Registrar cualquier salsa descartada antes de su hora por rotura de cadena de frío',
             'Barra', 'Encargado', '23:24'),
            ('Limpiar y desinfectar los recipientes de la barra al cierre',
             'Barra', 'Mostrador', '23:26'),
            ('Comprobar que ningún recipiente queda con resto de salsa al guardarlo',
             'Barra', 'Mostrador', '23:28'),
        ]),
    ],

    'Alérgenos y Cruzada': [
        ('CACAHUETE Y SÉSAMO', [
            ('Marcar la salsa macha (cacahuete y/o sésamo) en el cartel y separarla físicamente del resto',
             'Barra', 'Mostrador', '11:00'),
            ('Comprobar que la salsa macha (cacahuete y/o sésamo) no comparte utensilio con ninguna otra',
             'Barra', 'Mostrador', '11:05'),
            ('Revisar que el mostrador avisa siempre de la salsa macha (cacahuete y/o sésamo) al servir',
             'Mostrador', 'Mostrador', '11:10'),
            ('Limpiar y desinfectar licuadora y molcajete tras preparar la salsa macha (cacahuete y/o sésamo)',
             'Cocina', 'Plancha', '11:15'),
        ]),
        ('GLUTEN: MAÍZ FRENTE A HARINA', [
            ('Separar la tortilla de maíz (sin gluten) de la de harina de trigo: freidora, pinzas y superficie distintas',
             'Tortillería', 'Tortillero/a', '11:20'),
            ('Comprobar que la cesta de la freidora para tortilla de harina no toca la de tortilla de maíz',
             'Cocina', 'Plancha', '11:25'),
            ('Revisar la ficha de alérgenos de totopos y tacos dorados antes del servicio',
             'Cocina', 'Plancha', '11:30'),
            ('Etiquetar la zona de tortilla de harina para que el equipo no la confunda con la de maíz',
             'Tortillería', 'Tortillero/a', '11:35'),
        ]),
        ('LÁCTEOS Y FRUTOS DE CÁSCARA', [
            ('Revisar la ficha de alérgenos de los moles (frutos de cáscara, sésamo) antes del servicio',
             'Cocina', 'Plancha', '11:40'),
            ('Comprobar los lácteos (crema, queso) de cada guarnición en la ficha de alérgenos',
             'Cocina', 'Plancha', '11:45'),
            ('Separar los frutos de cáscara de repostería del resto de la barra de salsas',
             'Barra', 'Mostrador', '11:50'),
        ]),
        ('FICHAS Y CAMBIOS', [
            ('Comprobar que el mostrador sabe dar la información de alérgenos de los 14 de declaración obligatoria',
             'Mostrador', 'Mostrador', '11:55'),
            ('Registrar cada cambio de proveedor o de receta que altere una ficha de alérgenos',
             'Cocina', 'Encargado', '12:00'),
            ('Comprobar que la información de alérgenos es gratuita y accesible al cliente, por escrito',
             'Mostrador', 'Mostrador', '12:05'),
            ('Actualizar la carta y la app de delivery tras cualquier cambio de ficha de alérgenos',
             'Mostrador', 'Encargado', '12:10'),
        ]),
    ],

    # ------------------------------------------------------------------
    # 04 - 04-nixtamal-tortilla-guisados.xlsx
    # ------------------------------------------------------------------

    'Nixtamal y Molienda': [
        ('COCCIÓN Y REPOSO (SI APLICA)', [
            ('Pesar maíz y cal, y anotar la hora de inicio de cocción del nixtamal (maíz cocido con cal)',
             'Tortillería', 'Tortillero/a', '05:00'),
            ('Registrar el proveedor y el lote del maíz y de la cal utilizados',
             'Recepción', 'Tortillero/a', '05:30'),
            ('Anotar cualquier incidencia de la cocción: maíz duro, exceso de cal o tiempo fuera de rango',
             'Tortillería', 'Tortillero/a', '06:00'),
            ('Registrar el tiempo de reposo y la hora de lavado del nixtamal',
             'Tortillería', 'Tortillero/a', '06:30'),
            ('Comprobar que el maíz queda bien enjuagado antes de pasar a la molienda',
             'Tortillería', 'Tortillero/a', '07:00'),
        ]),
        ('MOLIENDA', [
            ('Limpiar y desinfectar el molino ANTES de moler: punto crítico de la tortillería (obrador de tortilla de maíz)',
             'Tortillería', 'Tortillero/a', '07:15'),
            ('Anotar la hora de molienda y la temperatura de conservación de la masa',
             'Tortillería', 'Tortillero/a', '07:45'),
            ('Comprobar la textura y el grosor de la masa recién molida',
             'Tortillería', 'Tortillero/a', '08:00'),
            ('Limpiar y desinfectar el molino DESPUÉS de moler y dejarlo seco',
             'Tortillería', 'Tortillero/a', '08:30'),
            ('Registrar cualquier avería o incidencia del molino para el parte de mantenimiento',
             'Tortillería', 'Encargado', '08:35'),
        ]),
        ('RENDIMIENTO Y CONSERVACIÓN', [
            ('Anotar la hora límite de la masa definida en tu APPCC (HACCP): ______',
             'Tortillería', 'Tortillero/a', '08:40'),
            ('Registrar el rendimiento: kg de maíz, kg de masa y número de tortillas',
             'Tortillería', 'Encargado', '08:45'),
            ('Comparar el rendimiento del día con la media de la semana y anotar la desviación',
             'Tortillería', 'Encargado', '08:50'),
            ('Comprobar la temperatura de conservación de la masa hasta su uso — anota la lectura: ____ °C',
             'Tortillería', 'Tortillero/a', '09:00'),
            ('Descartar la masa que supere la hora límite definida en tu APPCC (HACCP)',
             'Tortillería', 'Tortillero/a', '09:30'),
        ]),
    ],

    'Tortilla y Comal': [
        ('CALIBRADO', [
            ('Calibrar la tortilladora al arranque: grosor y peso por pieza',
             'Tortillería', 'Tortillero/a', '09:35'),
            ('Calentar el comal y comprobar que mantiene temperatura uniforme por zonas',
             'Tortillería', 'Tortillero/a', '09:40'),
            ('Ajustar el grosor de la tortilla de maíz frente al de la tortilla de harina',
             'Tortillería', 'Tortillero/a', '09:45'),
            ('Comprobar el peso de una muestra de tortillas de maíz al inicio del turno',
             'Tortillería', 'Tortillero/a', '09:50'),
        ]),
        ('PRODUCCIÓN Y MERMAS', [
            ('Anotar las mermas de tortilla de maíz y de harina por turno y su causa',
             'Tortillería', 'Tortillero/a', '12:30'),
            ('Doblar y guardar la tortilla de maíz en el cajón térmico hasta el servicio',
             'Tortillería', 'Tortillero/a', '11:00'),
            ('Registrar la producción total de tortilla de maíz y de harina del turno',
             'Tortillería', 'Encargado', '23:00'),
            ('Limpiar los restos de masa del comal y de la tortilladora entre tandas',
             'Tortillería', 'Tortillero/a', '15:00'),
        ]),
        ('TORTILLA COMPRADA', [
            ('Registrar la recepción de tortilla de maíz o de harina comprada: proveedor, lote y temperatura',
             'Recepción', 'Encargado', '09:00'),
            ('Comprobar que la tortilla de harina se almacena separada de la de maíz',
             'Almacén', 'Encargado', '09:05'),
            ('Revisar la fecha de caducidad de la tortilla comprada, de maíz o de harina, antes de usarla',
             'Almacén', 'Tortillero/a', '09:10'),
        ]),
    ],

    'Guisados y Rotación': [
        ('ELABORACIÓN', [
            ('Registrar el lote de carne y de verdura usado en cada guisado (cazuelas de relleno) del día',
             'Cocina', 'Encargado', '09:55'),
            ('Anotar hora de elaboración y hora de entrada en baño maría de cada guisado (cazuelas de relleno)',
             'Cocina', 'Plancha', '10:00'),
            ('Cocinar el pollo del guisado (tinga) a ≥ 74 °C durante ≥ 1 s en el centro',
             'Cocina', 'Plancha', '10:30'),
            ('Etiquetar cada guisado con nombre, fecha y hora de elaboración',
             'Cocina', 'Plancha', '10:45'),
        ]),
        ('BAÑO MARÍA', [
            ('Comprobar ≥ 63 °C en cada cazuela con dos lecturas por turno — anota la lectura: ____ °C',
             'Cocina', 'Plancha', '11:00'),
            ('Anotar la hora límite de cada guisado (cazuela de relleno) en servicio',
             'Cocina', 'Plancha', '11:05'),
            ('Remover cada guisado del baño maría para evitar zonas frías',
             'Cocina', 'Plancha', '12:00'),
            ('Recalentar a ≥ 74 °C durante 15 s en el centro, en menos de 1 hora desde que sale del frío',
             'Cocina', 'Plancha', '13:00'),
            ('Comprobar la rotación: primero lo elaborado antes (PEPS)',
             'Cocina', 'Encargado', '12:30'),
        ]),
        ('SOBRANTE Y MERMA', [
            ('Comprobar que ningún sobrante supera la hora límite definida en tu APPCC (HACCP)',
             'Cocina', 'Plancha', '22:45'),
            ('Etiquetar y abatir el sobrante apto; descartar el no apto y anotar la merma',
             'Cocina', 'Plancha', '23:00'),
            ('Registrar la merma de cada guisado del turno y su motivo',
             'Cocina', 'Encargado', '23:10'),
            ('Comparar la merma del día con la media de la semana y anotar la desviación',
             'Cocina', 'Encargado', '23:20'),
        ]),
    ],

}
